site_name: wechat-python-sdk
theme: yeti

site_url: http://wechat-python-sdk.com
repo_url: https://github.com/wechat-python-sdk
copyright: Copyright 2014-2016 Ace Kwok
markdown_extensions:
    - toc:
        permalink: True

extra:
  'version': 'v0.6.4 (20160725)'

pages:
  - '首页': 'index.md'
  - '快速上手':
    - '1. SDK 快速介绍': 'quickstart/intro.md'
    - '2. 官方接口': 'quickstart/official.md'
    - '3. WechatConf 详解': 'quickstart/wechatconf.md'
  - '官方接口':
    - '0. 前置介绍': 'official/intro.md'
    - '1. 接入指南': 'official/access.md'
    - '2. 消息管理': 'official/message.md'
    - '3. 自定义菜单': 'official/menu.md'
    - '4. 微信网页开发': 'official/website.md'
    - '5. 素材管理': 'official/material.md'
    - '6. 用户管理': 'official/user.md'
    - '7. 账号管理': 'official/account.md'
    - '8. 数据统计': 'official/datacube.md'
    - '9. 微信小店 ': 'official/store.md'
    - '10. 微信多客服功能': 'official/service.md'
  - 'API 文档':
    - '1. WechatConf': 'api/wechatconf.md'
    - '2. WechatMessage': 'api/wechatmessage.md'
    - '3. 异常类': 'api/exception.md'
  - 'FAQ': 'faq.md'
  - '关于项目': 'about/project.md'
  - '关于作者': 'about/author.md'
